spring:
  profiles:
    active: svil
    
  mvc:
   pathmatch:
    matching-strategy: ANT_PATH_MATCHER
     
info:
  app:
    name: '@project.artifactId@'
    version: '@project.version@'
    description: '@project.description@'
server:
  port: ${SERVER_PORT:8089}
  
  
configuration:

  wiam:
   end-point: ${WIAM0_ENDPOINT:https://localhost8081/wiam0}
    
  cach0:
    end-point: ${CACH0_ENDPOINT:https://localhost8082/cach0}
    
  otpv0:
    end-point: ${OTPV0_ENDPOINT:https://localhost8083/otpv0}
    
  docv0:
    end-point: ${DOCV0_ENDPOINT:https://localhosto8083/docv0}
    
    get-pdf: ${DOCV0_GETPDF:http://localhost:8080/docv0/getPdf}
    
  